<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="fastlane.lanes">
    
    
    
      
      <testcase classname="fastlane.lanes" name="0: default_platform" time="0.000475">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="1: version_get_podspec" time="0.000808">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="2: pod_lib_lint" time="63.987788">
        
          <failure message="/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/actions_helper.rb:67:in `execute_action'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'&#10;Fastfile:33:in `block (2 levels) in parsing_binding'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane.rb:33:in `call'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `execute'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/gems/fastlane-2.212.1/bin/fastlane:23:in `&lt;top (required)&gt;'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `load'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `&lt;main&gt;'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'&#10;/Users/qiuqixiang/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `&lt;main&gt;'&#10;&#10;Exit status of command 'bundle exec pod lib lint --allow-warnings' was 1 instead of 0.&#10;&#10; -&gt; WZFoundationExtension -&gt; WZFoundationExtension (3.2.1)&#10;    - WARN  | url: There was a problem validating the URL https://github.com/WZLYiOS/WZFoundationExtension.git.&#10;    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/WZLYiOS/WZNamespaceWrappable.git /var/folders/9k/r6jngj7x78g5h86k_kjzrmrc0000gn/T/d20240129-51422-1e1orao --template= --single-branch --depth 1 --branch 2.1.3&#10;&#10;Cloning into '/var/folders/9k/r6jngj7x78g5h86k_kjzrmrc0000gn/T/d20240129-51422-1e1orao'...&#10;fatal: unable to access 'https://github.com/WZLYiOS/WZNamespaceWrappable.git/': Failure when receiving data from the peer&#10;) during validation.&#10;&#10;[!] WZFoundationExtension did not pass validation, due to 1 error.&#10;You can use the `--no-clean` option to inspect any issue.&#10;" />
        
      </testcase>
    
  </testsuite>
</testsuites>
